MasterDetail/Models/ApplicationUser.cs
using System.Collections.Generic;
using System.Security.AccessControl;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace MasterDetail.Models
{
    // You can add profile data for the user by adding more properties to your ApplicationUser class, please visit http://go.microsoft.com/fwlink/?LinkID=317594 to learn more.
    public class ApplicationUser : IdentityUser
    {
        public async Task<ClaimsIdentity> GenerateUserIdentityAsync(UserManager<ApplicationUser> manager)
        {
            // Note the authenticationType must match the one defined in CookieAuthenticationOptions.AuthenticationType
            var userIdentity = await manager.CreateIdentityAsync(this, DefaultAuthenticationTypes.ApplicationCookie);
            // Add custom user claims here
            return userIdentity;
        }

        public string FirstName { get; set; }

        public string LastName { get; set; }

        public string Address { get; set; }

        public string City { get; set; }

        public string State { get; set; }

        public string ZipCode { get; set; }

        public string FullName => $"{FirstName} {LastName}";

        public string AddressBlock
        {
            get
            {
                var addressBlock = $"{Address}<br/>{City}, {State} {ZipCode}".Trim();
                return addressBlock == "<br/>," ? string.Empty : Address;
            }
        }

        public List<WorkOrder> WorkOrders { get; set; }

        public IEnumerable<SelectListItem> RoleList { get; set; }

    }
}

MasterDetail/Controllers/ApplicationUsersController.cs
using System;
using System.Data.Entity;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MasterDetail.Models;
using Microsoft.AspNet.Identity.Owin;

namespace MasterDetail.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ApplicationUsersController : Controller
    {
        private ApplicationUserManager _userManager;
        private ApplicationRoleManager _roleManager;

        public ApplicationUserManager UserManager
        {
            get { return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>(); }
            set { _userManager = value; }
        }

        public ApplicationRoleManager RoleManager
        {
            get { return _roleManager ?? HttpContext.GetOwinContext().Get<ApplicationRoleManager>(); }
            set { _roleManager = value; }
        }
        // private ApplicationDbContext db = new ApplicationDbContext();


        public ApplicationUsersController()
        {

        }

        public ApplicationUsersController(ApplicationUserManager userManager, ApplicationRoleManager roleManager)
        {
            UserManager = userManager;
            RoleManager = roleManager;
        }

        // GET: ApplicationUsers
        public async Task<ActionResult> Index()
        {
            return View(await UserManager.Users.ToListAsync());
        }


        // GET: ApplicationUsers/Edit/5
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var applicationUser = await UserManager.FindByIdAsync(id);
            if (applicationUser == null)
            {
                return HttpNotFound();
            }
            var userRoles = await UserManager.GetRolesAsync(applicationUser.Id);
            applicationUser.RoleList = RoleManager.Roles.ToList().Select(s => new SelectListItem
            {
                Selected = userRoles.Contains(s.Name),
                Text = s.Name,
                Value = s.Name
            });
            return View(applicationUser);
        }

        // POST: ApplicationUsers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id")] ApplicationUser applicationUser, params string[] rolesSelectedOnView)
        {
            if (ModelState.IsValid)
            {
                var rolesCurrentlyPersistedForUser = await UserManager.GetRolesAsync(applicationUser.Id);
                var isThisUserAnAdmin = rolesCurrentlyPersistedForUser.Contains("Admin");

                rolesSelectedOnView = rolesSelectedOnView ?? new string[] { };
                var isThisUserAnAdminDeselected = !rolesSelectedOnView.Contains("Admin");

                var role = await RoleManager.FindByNameAsync("Admin");
                var isOnlyOneUserAdmin = role.Users.Count == 1;

                applicationUser = await UserManager.FindByIdAsync(applicationUser.Id);
                applicationUser.RoleList = RoleManager.Roles.ToList().Select(s => new SelectListItem
                {
                    Selected = rolesCurrentlyPersistedForUser.Contains(s.Name),
                    Text = s.Name,
                    Value = s.Name
                });

                if (isThisUserAnAdmin && isThisUserAnAdminDeselected && isOnlyOneUserAdmin)
                {
                    ModelState.AddModelError("", "At least one user must retain the Admin role;you are attempting to delete the Admin role");
                    return View(applicationUser);
                }

               

                var result = await UserManager.AddToRolesAsync(applicationUser.Id, rolesSelectedOnView.Except(rolesCurrentlyPersistedForUser).ToArray());

                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View(applicationUser);
                }
                result = await UserManager.RemoveFromRolesAsync(applicationUser.Id, rolesCurrentlyPersistedForUser.Except(rolesSelectedOnView).ToArray());
                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View(applicationUser);
                }
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Something failed");
            return View(applicationUser);
        }


        public async Task<ActionResult> LockAccount([Bind(Include = "Id")] string id)
        {
            await UserManager.ResetAccessFailedCountAsync(id);
            await UserManager.SetLockoutEndDateAsync(id, DateTimeOffset.UtcNow.AddYears(100));
            return RedirectToAction("Index");
        }

        public async Task<ActionResult> UnlockAccount([Bind(Include = "Id")] string id)
        {
            await UserManager.ResetAccessFailedCountAsync(id);
            await UserManager.SetLockoutEndDateAsync(id, DateTimeOffset.UtcNow.AddYears(-1));
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                UserManager.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MasterDetail/Views/ApplicationUsers/Edit.cshtml
@model MasterDetail.Models.ApplicationUser

@{
    ViewBag.Title = "Edit User";
}

<h2>@ViewBag.Title</h2>


<div class="form-horizontal">

    <label class="control-label col-md-2">Full Name</label>
    <div class="col-md-10">
        <p class="form-control-static">@Model.FullName&nbsp;</p>
    </div>

    <label class="control-label col-md-2">User Name</label>
    <div class="col-md-10">
        <p class="form-control-static">@Model.UserName</p>
    </div>

    <label class="control-label col-md-2">Address</label>
    <div class="col-md-10">
        <p class="form-control-static">@Html.Raw(Model.AddressBlock)&nbsp;</p>
    </div>

    <div class="checkbox disabled col-md-offset-2">
        <label class="control-label">
            <input type="checkbox" checked="@Model.TwoFactorEnabled" disabled>
            Two-Factor Enabled
        </label>
    </div>

    <label class="control-label col-md-2">Email</label>
    <div class="col-md-10">
        <p class="form-control-static">@Model.Email</p>
    </div>

    <div class="checkbox disabled col-md-offset-2">
        <label class="control-label">
            <input type="checkbox" checked="@Model.EmailConfirmed" disabled>
            Email Confirmed
        </label>
    </div>

    <label class="control-label col-md-2">Phone Number</label>
    <div class="col-md-10">
        <p class="form-control-static">@Model.PhoneNumber&nbsp;</p>
    </div>

    <div class="checkbox disabled col-md-offset-2">
        <label class="control-label">
            <input type="checkbox" checked="@Model.PhoneNumberConfirmed" disabled>
            Phone Number Confirmed
        </label>
    </div>

    @* STATUS *@
    <label class="control-label col-md-2">Status</label>

    @*Cannot Lockout*@
    @if (!Model.LockoutEnabled)
    {
        <div class="col-md-10">
            <p class="form-control-static">This user cannot be locked out of his or her account.</p>
        </div>
    }


    @*Unlocked*@
    @if (Model.LockoutEnabled && (Model.LockoutEndDateUtc <= DateTime.Now || Model.LockoutEndDateUtc == null))
    {
        <div class="col-md-10">
            <p class="form-control-static">Unlocked</p>
        </div>

        <div class="col-md-offset-2">
            @using (Html.BeginForm("LockAccount", "ApplicationUsers", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary()
                @Html.HiddenFor(model => model.Id)
                <input type="submit" value="Lock Account" class="btn btn-danger" />
            }
        </div>

        <label class="control-label col-md-2">Access Failed Count</label>
        <div class="col-md-10">
            <p class="form-control-static">@Model.AccessFailedCount</p>
        </div>
    }


    @*Locked*@
    @if (Model.LockoutEnabled && (Model.LockoutEndDateUtc > DateTime.Now))
    {
        <div class="col-md-10">
            <p class="form-control-static">Locked-out until @Model.LockoutEndDateUtc (UTC)</p>
        </div>

        <div class="col-md-offset-2">
            @using (Html.BeginForm("UnlockAccount", "ApplicationUsers", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary()
                @Html.HiddenFor(model => model.Id)
                <input type="submit" value="Unlock Account" class="btn btn-success" />
            }
        </div>
    }

    @*Roles*@
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary()
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.Label("Roles", new { @class = "control-label col-sm-2" })
            <span class="col-sm-10">
                @foreach (var item in Model.RolesList)
                {
                    <input type="checkbox" name="RolesSelectedOnView" value="@item.Value" checked="@item.Selected" class="checkbox-inline" />
                    @Html.Label(item.Value, new { @class = "control-label" }) <br />
                }
            </span>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    }
</div>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MasterDetail/Views/ApplicationUsers/Index.cshtml
@model IEnumerable<MasterDetail.Models.ApplicationUser>

@{
    ViewBag.Title = "Index";
}

<h2>ViewBag.Title</h2>
 
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.State)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ZipCode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EmailConfirmed)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PasswordHash)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SecurityStamp)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PhoneNumberConfirmed)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TwoFactorEnabled)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LockoutEndDateUtc)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LockoutEnabled)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AccessFailedCount)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Address)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.City)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.State)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ZipCode)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EmailConfirmed)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PasswordHash)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SecurityStamp)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PhoneNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PhoneNumberConfirmed)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TwoFactorEnabled)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LockoutEndDateUtc)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LockoutEnabled)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AccessFailedCount)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id })  
        </td>
    </tr>
}

</table>